[project]
name = "visual-servoing"
version = "0.1.0"
description = "visual servoing master project"
authors = [
    { name = "Pedro Mendonca", email = "phavm@cin.ufpe.br"}
]
readme = "README.md"
license = { file = "LICENSE"}
requires-python = ">=3.10,<3.15"
urls = {Repository = "https://github.com/pedrohazevedovm/visual-servoing"}

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.15"

# 1. Dependências comuns (movidas lá de cima para cá)
numpy = "*"
opencv-python = "*"
matplotlib = "*"

# 2. Dependência Local (LightGlue)
lightglue = {path = "./LightGlue", develop = true}

# 3. Kornia (precisa estar aqui para respeitar o torch da GPU)
kornia = ">=0.6.11"

# 4. PyTorch com CUDA (Fonte Explicita)
# Dica: Use "*" para versão se você quer pegar a última disponível na URL cu130
# Ou fixe a versão exata que você viu no site (ex: 2.6.0 ou similar)
torch = {version = "*", source = "pytorch_gpu"}
torchvision = {version = "*", source = "pytorch_gpu"}

# --- SUA FONTE CUDA ---
[[tool.poetry.source]]
name = "pytorch_gpu"
url = "https://download.pytorch.org/whl/cu124"
# OBS: Se cu130 funcionar, use cu130. Se der erro 404, volte para cu124.
# O cu124 é garantido de ter binários estáveis para Windows atualmente.
priority = "explicit"